"""add initial tables

Revision ID: 2ae3b8e71f2a
Revises: 4771b6d15d49
Create Date: 2026-07-27 14:28:18.937297

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2ae3b8e71f2a'
down_revision: Union[str, Sequence[str], None] = '4771b6d15d49'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('events',
    sa.Column('id', sa.UUID(), nullable=False, comment='Уникальный идентификатор записи (UUID).'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='Дата и время создания записи в UTC.'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='Время последнего обновления'),
    sa.Column('start_datetime', sa.DateTime(timezone=True), nullable=False, comment='Дата и время начала события'),
    sa.Column('end_datetime', sa.DateTime(timezone=True), nullable=False, comment='Время окончания события'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('meetings',
    sa.Column('id', sa.UUID(), nullable=False, comment='Уникальный идентификатор записи (UUID).'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='Дата и время создания записи в UTC.'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='Время последнего обновления'),
    sa.Column('start_datetime', sa.DateTime(timezone=True), nullable=False, comment='Дата и время начала события'),
    sa.Column('end_datetime', sa.DateTime(timezone=True), nullable=False, comment='Время окончания события'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('projects',
    sa.Column('name', sa.String(length=255), nullable=False, comment='Название проекта.'),
    sa.Column('description', sa.String(length=512), nullable=True, comment='Описание проекта.'),
    sa.Column('id', sa.UUID(), nullable=False, comment='Уникальный идентификатор записи (UUID).'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='Дата и время создания записи в UTC.'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='Время последнего обновления'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('teams',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False, comment='Уникальный идентификатор записи (UUID).'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='Дата и время создания записи в UTC.'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='Время последнего обновления'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tasks',
    sa.Column('name', sa.String(length=124), nullable=False),
    sa.Column('description', sa.String(length=512), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False, comment='Уникальный идентификатор записи (UUID).'),
    sa.Column('parent_id', sa.UUID(), nullable=True, comment='Внешний ключ на родительскую задачу (самоссылка 1:N).'),
    sa.Column('project_id', sa.UUID(), nullable=True, comment='Внешний ключ на проект (1:N).'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='Дата и время создания записи в UTC.'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='Время последнего обновления'),
    sa.ForeignKeyConstraint(['parent_id'], ['tasks.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tasks_parent_id'), ['parent_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tasks_project_id'), ['project_id'], unique=False)

    op.create_table('team_projects',
    sa.Column('team_id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('team_id', 'project_id')
    )
    op.create_table('users',
    sa.Column('username', sa.String(length=255), nullable=False, comment='Имя пользователя. Обязательной поле.'),
    sa.Column('email', sa.String(length=255), nullable=False, comment='Электронная почта пользователя. Должна быть уникальной и обязательной.'),
    sa.Column('role', sa.String(length=50), nullable=False, comment="Роль пользователя в системе (например, 'admin', 'user'). Обязательное поле."),
    sa.Column('hashed_password', sa.String(length=128), nullable=False, comment='Хэшированный пароль пользователя, созданный с помощью bcrypt.'),
    sa.Column('refresh_token_hash', sa.String(length=255), nullable=True, comment='Хэш refresh_token для обеспечения безопасного logout и ротации сессий.'),
    sa.Column('team_id', sa.UUID(), nullable=True, comment='Внешний ключ на команду (1:N, пользователь в одной команде).'),
    sa.Column('id', sa.UUID(), nullable=False, comment='Уникальный идентификатор записи (UUID).'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='Дата и время создания записи в UTC.'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='Время последнего обновления'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('task_executors',
    sa.Column('id', sa.UUID(), nullable=True, comment='Не используется (для совместимости с BaseModel).'),
    sa.Column('estimate', sa.Integer(), nullable=True, comment='Оценка исполнителя за выполненую задачу'),
    sa.Column('user_id', sa.UUID(), nullable=False, comment='Внешний ключ на пользователя (обязательный, исполнитель).'),
    sa.Column('task_id', sa.UUID(), nullable=False, comment='Внешний ключ на задачу (обязательный, задача исполнителя).'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='Дата и время создания записи в UTC.'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='Время последнего обновления'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'task_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('task_executors')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    op.drop_table('team_projects')
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tasks_project_id'))
        batch_op.drop_index(batch_op.f('ix_tasks_parent_id'))

    op.drop_table('tasks')
    op.drop_table('teams')
    op.drop_table('projects')
    op.drop_table('meetings')
    op.drop_table('events')
    # ### end Alembic commands ###
