"""test

Revision ID: 6bcfb0c2d80f
Revises: 
Create Date: 2026-04-19 22:10:25.691562

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6bcfb0c2d80f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('buisnes_contexts',
    sa.Column('description', sa.String(length=1000), nullable=True, comment='Описание тура: маршрут, цель, особенности.'),
    sa.Column('all_price', sa.Integer(), nullable=True, comment='Общая стоимость тура.'),
    sa.Column('one_price', sa.Integer(), nullable=True, comment='Стоимость одного участника.'),
    sa.Column('id', sa.UUID(), nullable=False, comment='Уникальный идентификатор (UUID). Генерируется автоматически.'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('skills',
    sa.Column('name', sa.String(length=100), nullable=False, comment="Название навыка, например 'альпинизм', 'плавание'."),
    sa.Column('level', sa.String(length=50), nullable=False, comment="Уровень владения навыком: 'начальный', 'средний', 'продвинутый', 'эксперт'."),
    sa.Column('id', sa.UUID(), nullable=False, comment='Уникальный идентификатор (UUID). Генерируется автоматически.'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('username', sa.String(length=255), nullable=False, comment='Имя пользователя. Обязательной поле.'),
    sa.Column('email', sa.String(length=255), nullable=False, comment='Электронная почта пользователя. Должна быть уникальной и обязательной.'),
    sa.Column('role', sa.String(length=50), nullable=False, comment="Роль пользователя в системе (например, 'admin', 'user'). Обязательное поле."),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='Дата и время создания записи пользователя в UTC.'),
    sa.Column('hashed_password', sa.String(length=128), nullable=False, comment='Хэшированный пароль пользователя, созданный с помощью bcrypt.'),
    sa.Column('id', sa.UUID(), nullable=False, comment='Уникальный идентификатор (UUID). Генерируется автоматически.'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('profiles',
    sa.Column('user_id', sa.UUID(), nullable=False, comment='Ссылка на пользователя. Уникальна — один профиль на одного пользователя.'),
    sa.Column('first_name', sa.String(length=100), nullable=True, comment='Имя пользователя.'),
    sa.Column('last_name', sa.String(length=100), nullable=True, comment='Фамилия пользователя.'),
    sa.Column('age', sa.Integer(), nullable=True, comment='Возраст пользователя.'),
    sa.Column('phone', sa.String(length=15), nullable=True, comment='Номер телефона в международном формате, например +79991234567.'),
    sa.Column('me_description', sa.String(length=1000), nullable=True, comment='Описание пользователя, интересы, опыт и т.п.'),
    sa.Column('me_image', sa.String(length=500), nullable=True, comment='URL изображения профиля.'),
    sa.Column('blood_group', sa.String(length=4), nullable=True, comment="Группа крови, например 'A+', 'O-'"),
    sa.Column('allergies', sa.String(length=500), nullable=True, comment='Описание аллергий.'),
    sa.Column('emergency_contact', sa.String(length=500), nullable=True, comment='Контакт для экстренной связи (имя, телефон).'),
    sa.Column('insurance_number', sa.String(length=50), nullable=True, comment='Номер медицинской страховки.'),
    sa.Column('insurance_company', sa.String(length=100), nullable=True, comment='Название страховой компании.'),
    sa.Column('medical_features', sa.String(length=1000), nullable=True, comment='Дополнительные медицинские особенности (например, бронхит, диабет).'),
    sa.Column('id', sa.UUID(), nullable=False, comment='Уникальный идентификатор (UUID). Генерируется автоматически.'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('tours',
    sa.Column('description', sa.String(length=1000), nullable=True, comment='Описание тура'),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=False, comment='Дата и время начала тура в UTC.'),
    sa.Column('end_date', sa.DateTime(timezone=True), nullable=False, comment='Дата и время окончания тура в UTC.'),
    sa.Column('business_context_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False, comment='Уникальный идентификатор (UUID). Генерируется автоматически.'),
    sa.ForeignKeyConstraint(['business_context_id'], ['buisnes_contexts.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bookings',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('tour_id', sa.UUID(), nullable=False),
    sa.Column('booked_at', sa.DateTime(timezone=True), nullable=False, comment='Дата и время бронирования.'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='Статус бронирования: pending, confirmed, cancelled.'),
    sa.Column('id', sa.UUID(), nullable=False, comment='Уникальный идентификатор (UUID). Генерируется автоматически.'),
    sa.ForeignKeyConstraint(['tour_id'], ['tours.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'tour_id', 'id')
    )
    op.create_table('profile_skills',
    sa.Column('profile_id', sa.UUID(), nullable=False),
    sa.Column('skill_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('profile_id', 'skill_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('profile_skills')
    op.drop_table('bookings')
    op.drop_table('tours')
    op.drop_table('profiles')
    op.drop_table('users')
    op.drop_table('skills')
    op.drop_table('buisnes_contexts')
    # ### end Alembic commands ###
