"""обновление моделей: добавление встреч и событий

Revision ID: 91983037ff5d
Revises: 2ae3b8e71f2a
Create Date: 2026-08-01 20:46:06.877955

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '91983037ff5d'
down_revision: Union[str, Sequence[str], None] = '2ae3b8e71f2a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('meeting_teams',
    sa.Column('meeting_id', sa.UUID(), nullable=False),
    sa.Column('team_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('meeting_id', 'team_id')
    )
    op.create_table('comments',
    sa.Column('description', sa.String(length=512), nullable=False),
    sa.Column('author_id', sa.UUID(), nullable=False, comment='Внешний ключ на автора.'),
    sa.Column('task_id', sa.UUID(), nullable=True, comment='Внешний ключ на задачу.'),
    sa.Column('id', sa.UUID(), nullable=False, comment='Уникальный идентификатор записи (UUID).'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='Дата и время создания записи в UTC.'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='Время последнего обновления'),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_comments_author_id'), ['author_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_comments_task_id'), ['task_id'], unique=False)

    op.create_table('meeting_participants',
    sa.Column('meeting_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('meeting_id', 'user_id')
    )
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=255), nullable=False, comment='Название события.'))
        batch_op.add_column(sa.Column('description', sa.String(length=512), nullable=True, comment='Описание события.'))

    with op.batch_alter_table('meetings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=255), nullable=False, comment='Название встречи.'))
        batch_op.add_column(sa.Column('description', sa.String(length=512), nullable=True, comment='Описание встречи.'))

    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('estimate', sa.Integer(), nullable=True, comment='Оценка задачи'))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_column('estimate')

    with op.batch_alter_table('meetings', schema=None) as batch_op:
        batch_op.drop_column('description')
        batch_op.drop_column('name')

    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_column('description')
        batch_op.drop_column('name')

    op.drop_table('meeting_participants')
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_comments_task_id'))
        batch_op.drop_index(batch_op.f('ix_comments_author_id'))

    op.drop_table('comments')
    op.drop_table('meeting_teams')
    # ### end Alembic commands ###
